// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-SiZm8-9qdj6TXqFV5Xj6p6yn11aiu8',
    appId: '1:763521872318:web:dc0e75887efd49628489ef',
    messagingSenderId: '763521872318',
    projectId: 'visitorslogdb',
    authDomain: 'visitorslogdb.firebaseapp.com',
    storageBucket: 'visitorslogdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EUfNOpvThDrRgzup_F6XZhmarxB1WaU',
    appId: '1:763521872318:android:1a809de5e6f13d148489ef',
    messagingSenderId: '763521872318',
    projectId: 'visitorslogdb',
    storageBucket: 'visitorslogdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8qpK65XOPoytfPlD9aKyCkLemeC_i86w',
    appId: '1:763521872318:ios:d0272b1636c925a58489ef',
    messagingSenderId: '763521872318',
    projectId: 'visitorslogdb',
    storageBucket: 'visitorslogdb.appspot.com',
    iosClientId: '763521872318-v0kim2fbs7kk2fp3obfsp6tij82t5l13.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitorsLogProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8qpK65XOPoytfPlD9aKyCkLemeC_i86w',
    appId: '1:763521872318:ios:d0272b1636c925a58489ef',
    messagingSenderId: '763521872318',
    projectId: 'visitorslogdb',
    storageBucket: 'visitorslogdb.appspot.com',
    iosClientId: '763521872318-v0kim2fbs7kk2fp3obfsp6tij82t5l13.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitorsLogProject',
  );
}
